/**
 * Announcer voice cues — booming SF II-style game shouts.
 *
 * Plays pre-rendered MP3s from public/audio/voices/announcer/<key>.mp3 if
 * they exist (generated by scripts/generate-voice-azure.ts). Silently no-ops
 * if files are missing so the game still works during dev.
 *
 * Note: this is intentionally NOT routed through SpeechSynthesis. Announcer
 * lines are short SF II-style shouts ("FIGHT!", "K.O.!") that sound bad
 * through robotic OS voices — they only land with the Azure Neural files.
 */

let enabled = true
let currentAudio: HTMLAudioElement | null = null

const knownMissing = new Set<string>()

function play(key: string, volume = 0.95) {
  if (!enabled) return
  if (knownMissing.has(key)) return
  if (currentAudio) {
    currentAudio.pause()
    currentAudio.currentTime = 0
    currentAudio = null
  }
  const a = new Audio(`/audio/voices/announcer/${key}.mp3`)
  a.volume = volume
  a.addEventListener('error', () => knownMissing.add(key))
  a.play().catch(() => knownMissing.add(key))
  currentAudio = a
}

function playStage(scenarioId: string) {
  if (!enabled) return
  const cacheKey = `stage:${scenarioId}`
  if (knownMissing.has(cacheKey)) return
  if (currentAudio) {
    currentAudio.pause()
    currentAudio.currentTime = 0
    currentAudio = null
  }
  const a = new Audio(`/audio/voices/stages/${scenarioId}.mp3`)
  a.volume = 0.9
  a.addEventListener('error', () => knownMissing.add(cacheKey))
  a.play().catch(() => knownMissing.add(cacheKey))
  currentAudio = a
}

export const Announcer = {
  fight()      { play('fight') },
  ko()         { play('ko') },
  combo()      { play('combo') },
  crit()       { play('crit') },
  ultimate()   { play('ultimate') },
  perfect()    { play('perfect') },
  timeup()     { play('timeup') },
  round(n: 1 | 2 | 3) { play(`round${n}`) },
  reading()    { play('reading') },
  stage(id: string)   { playStage(id) },

  isEnabled() { return enabled },
  setEnabled(v: boolean) {
    enabled = v
    if (!v && currentAudio) {
      currentAudio.pause()
      currentAudio = null
    }
  },
  toggle() { Announcer.setEnabled(!enabled) },
}
