/**
 * Announcer voice cues — booming SF II-style game shouts.
 *
 * Plays pre-rendered MP3s from public/audio/voices/announcer/<key>.mp3 if
 * they exist (generated by scripts/generate-voice-azure.ts). Silently no-ops
 * if files are missing so the game still works during dev.
 *
 * Note: this is intentionally NOT routed through SpeechSynthesis. Announcer
 * lines are short SF II-style shouts ("FIGHT!", "K.O.!") that sound bad
 * through robotic OS voices — they only land with the Azure Neural files.
 */

import { fightAudio } from '../audio'

let enabled = true
let currentAudio: HTMLAudioElement | null = null

const knownMissing = new Set<string>()

// Try the processed voice bus (radio EQ + plate reverb + music duck) first;
// fall back to a raw <audio> element if Web-Audio routing isn't available.
function playUrl(url: string, cacheKey: string, volume: number) {
  if (knownMissing.has(cacheKey)) return
  if (currentAudio) {
    currentAudio.pause()
    currentAudio.currentTime = 0
    currentAudio = null
  }
  const processed = fightAudio.playVoice(url, { volume })
  const a = processed ?? new Audio(url)
  if (!processed) {
    a.volume = volume
    a.play().catch(() => knownMissing.add(cacheKey))
  }
  a.addEventListener('error', () => knownMissing.add(cacheKey))
  currentAudio = a
}

function play(key: string, volume = 0.95) {
  if (!enabled) return
  playUrl(`/audio/voices/announcer/${key}.mp3`, key, volume)
}

function playStage(scenarioId: string) {
  if (!enabled) return
  playUrl(`/audio/voices/stages/${scenarioId}.mp3`, `stage:${scenarioId}`, 0.9)
}

export const Announcer = {
  fight()      { play('fight') },
  ko()         { play('ko') },
  combo()      { play('combo') },
  crit()       { play('crit') },
  ultimate()   { play('ultimate') },
  perfect()    { play('perfect') },
  timeup()     { play('timeup') },
  round(n: 1 | 2 | 3) { play(`round${n}`) },
  reading()    { play('reading') },
  stage(id: string)   { playStage(id) },

  isEnabled() { return enabled },
  setEnabled(v: boolean) {
    enabled = v
    if (!v && currentAudio) {
      currentAudio.pause()
      currentAudio = null
    }
  },
  toggle() { Announcer.setEnabled(!enabled) },
}
