import { describe, expect, it } from 'vitest'
import { existsSync, readdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { BROKEN_AT, byDrawing, scoreFighter, type CelScore } from '../../../../scripts/lib/ghost-score'
import { ROSTER } from '../../../fighthud/select/roster'

/** The six skins a player can actually pick. Read from the shipped roster, never hardcoded. */
const SELECTABLE = new Set(ROSTER.map((r) => r.skin))

/**
 * Double-exposure gate for synthesised in-between cels.
 *
 * WHAT SHIPPED, AND WHY NOTHING CAUGHT IT
 * `inbetween.ts` builds in-between cels by optical-flow morphing two hand-drawn
 * keys. It forward-splats colour (correct) but cross-dissolves ALPHA linearly, so
 * wherever the flow finds no correspondence — a limb crossing in front of another,
 * a body rotating through an arc — one key is opaque and the other transparent
 * across a whole region and the dissolve lands it at alpha≈127: a 50%-translucent
 * ghost limb with the background visible through it. Half of every synthesised cel
 * on the shipping roster (73 of 145) was in that state, including every frame of
 * the juggle — the clip that replays on every combo.
 *
 * Every gate in this suite was blind to it, and structurally so:
 *   - `locomotionRichness` pins cel COUNTS. Eight cels of which four are ghosts
 *     scores identically to eight good ones — it was actively rewarding the defect.
 *   - `contactCel` / `animationCadence` pin WHICH cel is on screen WHEN. A ghost is
 *     on screen exactly when it should be.
 *   - `manifestSpecDrift` pins manifest against spec. The manifest was correct;
 *     the pixels were not.
 * None of them look at pixels, so none of them could see it. This one does.
 *
 * WHAT THIS GATE ASSERTS
 * No shipped in-between may sit in the double-exposure band. See ghost-score.ts
 * for the calibration — the threshold came from a blind critique whose verdicts
 * the score separated with no overlap, not from a number that looked reasonable.
 *
 * ⚠️ IF YOU ARE HERE BECAUSE THIS WENT RED
 * Do NOT fix it by tuning the morph until the number drops. That was tried:
 * alpha-sharpening moved walk tweens from 34-41% into the clean band and the same
 * critic graded the output WORSE than the ghost it replaced, because it had swapped
 * soft translucency for ragged, doubled silhouette edges the score cannot see.
 * Raising `flowRes` 128→256 also made it worse. The morph fails in proportion to
 * the GEOMETRIC DISTANCE between the two source drawings — rotation, limb-crossing,
 * self-occlusion — and no parameter of it can invent a pose that exists in neither
 * source. The two honest fixes are: stop tweening that clip and hold its keys
 * (see the block comment in frame-spec.ts), or draw the in-between by hand.
 */

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(HERE, '../../../..')
const PUBLIC = resolve(ROOT, 'public')
const FIGHTER_DIR = resolve(PUBLIC, 'fighters')

/**
 * Population is READ FROM DISK, never hardcoded. A hardcoded list is how a gate
 * silently stops covering a fighter that someone adds later — and this suite has
 * already shipped that exact failure once, in a gate whose own comment warned
 * against it. Every fighter with a manifest is graded, playable or not: an
 * unplayable skin's cels are still generated by the same morph, and letting them
 * rot means the defect reappears the moment one is promoted to the roster.
 */
const FIGHTERS: string[] = existsSync(FIGHTER_DIR)
  ? readdirSync(FIGHTER_DIR, { withFileTypes: true })
      .filter((d) => d.isDirectory() && existsSync(resolve(FIGHTER_DIR, d.name, 'assets.json')))
      .map((d) => d.name)
      .sort()
  : []

let rows: CelScore[] = []
for (const id of FIGHTERS) {
  const r = await scoreFighter(id, PUBLIC)
  if (r) rows.push(...r)
}
rows = byDrawing(rows)
const tweens = rows.filter((r) => r.tween)
const keys = rows.filter((r) => !r.tween)
const fmt = (r: CelScore): string => `${r.fighter}/${r.clip}/${r.name} ${r.score.toFixed(1)}%`

describe('synthesised in-between cels are not double-exposed', () => {
  /**
   * Vacuity guards. Every assertion below is a filter over `rows`, so an empty
   * or tween-free `rows` would make all of them pass while measuring nothing —
   * which is precisely the state this file exists to make impossible. These fail
   * loudly if the atlases stop being readable, the population collapses, or the
   * `tw-` naming convention changes out from under the detector.
   */
  it('measured a real population', () => {
    expect(FIGHTERS.length).toBeGreaterThanOrEqual(6)
    expect(rows.length).toBeGreaterThan(300)
    expect(keys.length).toBeGreaterThan(300)
    // Tweens still exist: idle/crouch/block/lp/mp keep theirs because they morph
    // cleanly. If this hits zero, someone deleted the remaining tweens and this
    // gate silently stopped guarding anything.
    expect(tweens.length).toBeGreaterThan(20)
  })

  /**
   * POSITIVE CONTROL — the load-bearing one.
   *
   * Hand-drawn keys are known-good by construction: a human drew them, they were
   * never morphed. If the score cannot put them well under the threshold then it
   * is measuring noise (or the cutoffs are wrong), and every pass below is
   * meaningless. This is what makes the gate's green mean something.
   */
  it('scores hand-drawn keys far below the threshold', () => {
    const worst = keys.slice().sort((a, b) => b.score - a.score)
    // Exactly zero, not merely small. Erosion by RADIUS is arithmetically
    // incapable of surviving an anti-aliased rim, so a hand-drawn cel MUST read
    // 0. If this ever reads non-zero, the detector has started responding to
    // something other than morph residue and nothing below it can be trusted.
    expect(worst[0].score, `worst hand-drawn key: ${fmt(worst[0])}`).toBe(0)
  })

  /** The shipping assertion — a one-way ratchet, not a classification. */
  it('ships no double-exposed in-between', () => {
    const broken = tweens.filter((r) => r.score >= BROKEN_AT).sort((a, b) => b.score - a.score)
    expect(
      broken.map(fmt),
      broken.length
        ? `${broken.length} in-between(s) got WORSE than the current high-water mark. Do NOT ` +
            'raise BROKEN_AT to admit them, and do NOT tune the morph to silence this — see the ' +
            'warning at the top of this file. Either drop the tween and hold the clip\'s keys, ' +
            'or draw the in-between by hand.'
        : '',
    ).toEqual([])
  })

  /**
   * The tighter line, on the population that actually reaches a player.
   *
   * The ratchet above covers all 11 manifests; only six are selectable. Pinning
   * the shipping six separately means a non-selectable card skin drifting cannot
   * quietly buy headroom for the fighters a buyer really sees.
   */
  it('holds the selectable roster tighter than the full manifest set', () => {
    const shipping = tweens.filter((r) => SELECTABLE.has(r.fighter))
    expect(shipping.length, 'no selectable in-betweens were scored — the filter is wrong').toBeGreaterThan(20)
    const worst = shipping.slice().sort((a, b) => b.score - a.score)[0]
    expect(worst.score, `worst SHIPPING in-between: ${fmt(worst)}`).toBeLessThan(5)
  })

  /**
   * Characterization pin with a deliberate margin, so a partial regression reds
   * here before it reaches the shipping threshold above. Strict `<` — a change
   * that merely ties the current worst is still a change and should be looked at.
   *
   * NAMING THE DEFICIT, because a green tick must not be read as "all clean".
   * Hand-drawn cels read 0.0%. EVERY surviving in-between reads above 0, so
   * ghosting is a continuum inherent to the morph, not a binary this gate has
   * eliminated. What survives is only the three settle clips — idle, crouch,
   * block — whose two source drawings are geometrically close, which is exactly
   * the case the morph handles. A blind critic graded the idle tweens clean but
   * flagged minor doubling on thin trailing accessories (sash tails, drawstrings),
   * which is what the residue here is. crouch and block have NOT been visually
   * judged. So this pin holds the line where the art is today, and a non-zero
   * reading is a standing invitation to draw these by hand rather than evidence
   * that morphing them is fine.
   */
  it('keeps the surviving in-betweens comfortably inside the clean band', () => {
    const worst = tweens.slice().sort((a, b) => b.score - a.score)[0]
    expect(worst.score, `worst surviving in-between: ${fmt(worst)}`).toBeLessThan(6)
  })

  /**
   * Scope pin. The clips below were measured broken on every fighter and had
   * their tweens removed in favour of held keys (frame-spec.ts documents the
   * reasoning and the two failed fixes). Re-adding a tween to any of them
   * reintroduces the defect, so name them explicitly rather than relying on the
   * threshold to catch it after the fact — a newly-added tween on a fighter whose
   * palette happens to hide the ghost could otherwise slip in under the threshold.
   */
  it('does not re-tween the clips that cannot be morphed', () => {
    const CANNOT_MORPH = ['walk-fwd', 'walk-back', 'juggle', 'knockdown', 'hurt', 'hp', 'lp', 'mp']
    const offenders = tweens.filter((r) => CANNOT_MORPH.includes(r.clip)).map(fmt)
    expect(
      offenders,
      'these clips rotate the body or cross limbs between keys, which optical flow ' +
        'cannot represent at any resolution; they hold hand-drawn keys instead',
    ).toEqual([])
  })
})
